# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_testthat_tests <- function() {
    .Call(`_graphs_run_testthat_tests`)
}

